name: Run Python Script

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m !pip install requests
          python -m !pip install twilio
      - name: Run the script
        run: python sms_alert.py
